name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        with:
          repository: 'RuslanT25/RuslanT25'

      - name: Generate Snake GIF
        uses: Platane/snk@v2
        with:
          github_user_name: RuslanT25
          outputs: both

      - name: Commit and Push Snake GIF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Generated snake gif"
          git push origin main
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: RuslanT25/RuslanT25
          publish_dir: ./dist
          publish_branch: output
